---
- name: Extend Filesystem
  hosts: all
  tasks:
    - name: Resize Logical Volume
      command: lvextend -L +{{ desired_size }}G {{ lv_path }}
      when: ansible_facts['ansible_mounts'][0]['device'] == lv_device
      async: 3600
      poll: 0
      become: yes

    - name: Wait for LV resize to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 3600
      delay: 1
      when: ansible_facts['ansible_mounts'][0]['device'] == lv_device
      become: yes

    - name: Resize the Filesystem
      command: resize2fs {{ mount_point }}
      when: ansible_facts['ansible_mounts'][0]['device'] == lv_device
      become: yes

