- name: Create Aplication Load Balancer
  hosts: all
  become: true

  tasks:
    - include_vars:
        file: applicationlbvars.yml

    - name: Create LB Security Group
      amazon.aws.ec2_security_group:
        state: present
        name: "{{ name }}_lb_sg"
        description: Security group for LB
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        purge_rules: no
        purge_tags: no
        rules:
           - rule_desc: Allow inbound traffic
             proto: tcp
             from_port: "{{ listener_port }}"
             to_port: "{{ listener_port }}"
             cidr_ip: "{{ incoming_cidr_ip }}"
        tags:
           Name: "{{ name }}-sg-lb"
      register: lb_security_group

    - name: Create LB Target Group
      community.aws.elb_target_group:
        state: present
        name: "{{ name }}-tg"
        region: "{{ region }}"
        protocol: http
        port: "{{ instance_port }}"
        vpc_id: "{{ vpc_id }}"
      register: target_group

    - name: Create Application Load Balancer
      amazon.aws.elb_application_lb:
        state: present
        name: "{{ name }}-lb"
        region: "{{ region }}"
        scheme: internet-facing
        subnets: "{{ subnets }}"
        security_groups:
          - "{{ lb_security_group.group_id }}"
        purge_listeners: yes
        listeners:
          - Protocol: "{{ protocol }}"
            Port: "{{ listener_port }}"
            DefaultActions:
              - Type: forward
                TargetGroupName: "{{ target_group.target_group_name }}"
